/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as FantasyRouteImport } from './routes/fantasy'
import { Route as MatchCenterRouteImport } from './routes/match-center'
import { Route as NewsRouteImport } from './routes/news'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminImportRouteImport } from './routes/admin.import'
import { Route as FantasyIndexRouteImport } from './routes/fantasy.index'
import { Route as FantasyPointsRouteImport } from './routes/fantasy.points'
import { Route as FantasyTeamRouteImport } from './routes/fantasy.team'
import { Route as FantasyTransfersRouteImport } from './routes/fantasy.transfers'
import { Route as MatchCenterIndexRouteImport } from './routes/match-center.index'
import { Route as MatchCenterTeamIdRouteImport } from './routes/match-center.$teamId'
import { Route as PlayersIndexRouteImport } from './routes/players.index'
import { Route as PlayersPlayerIdRouteImport } from './routes/players.$playerId'
import { Route as FantasyLeaguesIndexRouteImport } from './routes/fantasy.leagues.index'
import { Route as FantasyLeaguesLeagueIdRouteImport } from './routes/fantasy.leagues.$leagueId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const FantasyRoute = FantasyRouteImport.update({
  id: '/fantasy',
  path: '/fantasy',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchCenterRoute = MatchCenterRouteImport.update({
  id: '/match-center',
  path: '/match-center',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminImportRoute = AdminImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AdminRoute,
} as any)
const FantasyIndexRoute = FantasyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FantasyRoute,
} as any)
const FantasyPointsRoute = FantasyPointsRouteImport.update({
  id: '/points',
  path: '/points',
  getParentRoute: () => FantasyRoute,
} as any)
const FantasyTeamRoute = FantasyTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => FantasyRoute,
} as any)
const FantasyTransfersRoute = FantasyTransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => FantasyRoute,
} as any)
const MatchCenterIndexRoute = MatchCenterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MatchCenterRoute,
} as any)
const MatchCenterTeamIdRoute = MatchCenterTeamIdRouteImport.update({
  id: '/$teamId',
  path: '/$teamId',
  getParentRoute: () => MatchCenterRoute,
} as any)
const PlayersIndexRoute = PlayersIndexRouteImport.update({
  id: '/players/',
  path: '/players/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersPlayerIdRoute = PlayersPlayerIdRouteImport.update({
  id: '/players/$playerId',
  path: '/players/$playerId',
  getParentRoute: () => rootRouteImport,
} as any)
const FantasyLeaguesIndexRoute = FantasyLeaguesIndexRouteImport.update({
  id: '/leagues/',
  path: '/leagues/',
  getParentRoute: () => FantasyRoute,
} as any)
const FantasyLeaguesLeagueIdRoute = FantasyLeaguesLeagueIdRouteImport.update({
  id: '/leagues/$leagueId',
  path: '/leagues/$leagueId',
  getParentRoute: () => FantasyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/fantasy': typeof FantasyRouteWithChildren
  '/match-center': typeof MatchCenterRouteWithChildren
  '/news': typeof NewsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/videos': typeof VideosRoute
  '/admin/import': typeof AdminImportRoute
  '/fantasy/points': typeof FantasyPointsRoute
  '/fantasy/team': typeof FantasyTeamRoute
  '/fantasy/transfers': typeof FantasyTransfersRoute
  '/match-center/$teamId': typeof MatchCenterTeamIdRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/admin/': typeof AdminIndexRoute
  '/fantasy/': typeof FantasyIndexRoute
  '/match-center/': typeof MatchCenterIndexRoute
  '/players/': typeof PlayersIndexRoute
  '/fantasy/leagues/$leagueId': typeof FantasyLeaguesLeagueIdRoute
  '/fantasy/leagues/': typeof FantasyLeaguesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/news': typeof NewsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/videos': typeof VideosRoute
  '/admin/import': typeof AdminImportRoute
  '/fantasy/points': typeof FantasyPointsRoute
  '/fantasy/team': typeof FantasyTeamRoute
  '/fantasy/transfers': typeof FantasyTransfersRoute
  '/match-center/$teamId': typeof MatchCenterTeamIdRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/admin': typeof AdminIndexRoute
  '/fantasy': typeof FantasyIndexRoute
  '/match-center': typeof MatchCenterIndexRoute
  '/players': typeof PlayersIndexRoute
  '/fantasy/leagues/$leagueId': typeof FantasyLeaguesLeagueIdRoute
  '/fantasy/leagues': typeof FantasyLeaguesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/fantasy': typeof FantasyRouteWithChildren
  '/match-center': typeof MatchCenterRouteWithChildren
  '/news': typeof NewsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/videos': typeof VideosRoute
  '/admin/import': typeof AdminImportRoute
  '/fantasy/points': typeof FantasyPointsRoute
  '/fantasy/team': typeof FantasyTeamRoute
  '/fantasy/transfers': typeof FantasyTransfersRoute
  '/match-center/$teamId': typeof MatchCenterTeamIdRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/admin/': typeof AdminIndexRoute
  '/fantasy/': typeof FantasyIndexRoute
  '/match-center/': typeof MatchCenterIndexRoute
  '/players/': typeof PlayersIndexRoute
  '/fantasy/leagues/$leagueId': typeof FantasyLeaguesLeagueIdRoute
  '/fantasy/leagues/': typeof FantasyLeaguesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/auth'
    | '/fantasy'
    | '/match-center'
    | '/news'
    | '/onboarding'
    | '/profile'
    | '/videos'
    | '/admin/import'
    | '/fantasy/points'
    | '/fantasy/team'
    | '/fantasy/transfers'
    | '/match-center/$teamId'
    | '/players/$playerId'
    | '/admin/'
    | '/fantasy/'
    | '/match-center/'
    | '/players/'
    | '/fantasy/leagues/$leagueId'
    | '/fantasy/leagues/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-login'
    | '/auth'
    | '/news'
    | '/onboarding'
    | '/profile'
    | '/videos'
    | '/admin/import'
    | '/fantasy/points'
    | '/fantasy/team'
    | '/fantasy/transfers'
    | '/match-center/$teamId'
    | '/players/$playerId'
    | '/admin'
    | '/fantasy'
    | '/match-center'
    | '/players'
    | '/fantasy/leagues/$leagueId'
    | '/fantasy/leagues'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-login'
    | '/auth'
    | '/fantasy'
    | '/match-center'
    | '/news'
    | '/onboarding'
    | '/profile'
    | '/videos'
    | '/admin/import'
    | '/fantasy/points'
    | '/fantasy/team'
    | '/fantasy/transfers'
    | '/match-center/$teamId'
    | '/players/$playerId'
    | '/admin/'
    | '/fantasy/'
    | '/match-center/'
    | '/players/'
    | '/fantasy/leagues/$leagueId'
    | '/fantasy/leagues/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AuthRoute: typeof AuthRoute
  FantasyRoute: typeof FantasyRouteWithChildren
  MatchCenterRoute: typeof MatchCenterRouteWithChildren
  NewsRoute: typeof NewsRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  VideosRoute: typeof VideosRoute
  PlayersPlayerIdRoute: typeof PlayersPlayerIdRoute
  PlayersIndexRoute: typeof PlayersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fantasy': {
      id: '/fantasy'
      path: '/fantasy'
      fullPath: '/fantasy'
      preLoaderRoute: typeof FantasyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match-center': {
      id: '/match-center'
      path: '/match-center'
      fullPath: '/match-center'
      preLoaderRoute: typeof MatchCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/import': {
      id: '/admin/import'
      path: '/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AdminImportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/fantasy/': {
      id: '/fantasy/'
      path: '/'
      fullPath: '/fantasy/'
      preLoaderRoute: typeof FantasyIndexRouteImport
      parentRoute: typeof FantasyRoute
    }
    '/fantasy/points': {
      id: '/fantasy/points'
      path: '/points'
      fullPath: '/fantasy/points'
      preLoaderRoute: typeof FantasyPointsRouteImport
      parentRoute: typeof FantasyRoute
    }
    '/fantasy/team': {
      id: '/fantasy/team'
      path: '/team'
      fullPath: '/fantasy/team'
      preLoaderRoute: typeof FantasyTeamRouteImport
      parentRoute: typeof FantasyRoute
    }
    '/fantasy/transfers': {
      id: '/fantasy/transfers'
      path: '/transfers'
      fullPath: '/fantasy/transfers'
      preLoaderRoute: typeof FantasyTransfersRouteImport
      parentRoute: typeof FantasyRoute
    }
    '/match-center/': {
      id: '/match-center/'
      path: '/'
      fullPath: '/match-center/'
      preLoaderRoute: typeof MatchCenterIndexRouteImport
      parentRoute: typeof MatchCenterRoute
    }
    '/match-center/$teamId': {
      id: '/match-center/$teamId'
      path: '/$teamId'
      fullPath: '/match-center/$teamId'
      preLoaderRoute: typeof MatchCenterTeamIdRouteImport
      parentRoute: typeof MatchCenterRoute
    }
    '/players/': {
      id: '/players/'
      path: '/players'
      fullPath: '/players/'
      preLoaderRoute: typeof PlayersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/$playerId': {
      id: '/players/$playerId'
      path: '/players/$playerId'
      fullPath: '/players/$playerId'
      preLoaderRoute: typeof PlayersPlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fantasy/leagues/': {
      id: '/fantasy/leagues/'
      path: '/leagues'
      fullPath: '/fantasy/leagues/'
      preLoaderRoute: typeof FantasyLeaguesIndexRouteImport
      parentRoute: typeof FantasyRoute
    }
    '/fantasy/leagues/$leagueId': {
      id: '/fantasy/leagues/$leagueId'
      path: '/leagues/$leagueId'
      fullPath: '/fantasy/leagues/$leagueId'
      preLoaderRoute: typeof FantasyLeaguesLeagueIdRouteImport
      parentRoute: typeof FantasyRoute
    }
  }
}

interface AdminRouteChildren {
  AdminImportRoute: typeof AdminImportRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminImportRoute: AdminImportRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface FantasyRouteChildren {
  FantasyPointsRoute: typeof FantasyPointsRoute
  FantasyTeamRoute: typeof FantasyTeamRoute
  FantasyTransfersRoute: typeof FantasyTransfersRoute
  FantasyIndexRoute: typeof FantasyIndexRoute
  FantasyLeaguesLeagueIdRoute: typeof FantasyLeaguesLeagueIdRoute
  FantasyLeaguesIndexRoute: typeof FantasyLeaguesIndexRoute
}

const FantasyRouteChildren: FantasyRouteChildren = {
  FantasyPointsRoute: FantasyPointsRoute,
  FantasyTeamRoute: FantasyTeamRoute,
  FantasyTransfersRoute: FantasyTransfersRoute,
  FantasyIndexRoute: FantasyIndexRoute,
  FantasyLeaguesLeagueIdRoute: FantasyLeaguesLeagueIdRoute,
  FantasyLeaguesIndexRoute: FantasyLeaguesIndexRoute,
}

const FantasyRouteWithChildren =
  FantasyRoute._addFileChildren(FantasyRouteChildren)

interface MatchCenterRouteChildren {
  MatchCenterTeamIdRoute: typeof MatchCenterTeamIdRoute
  MatchCenterIndexRoute: typeof MatchCenterIndexRoute
}

const MatchCenterRouteChildren: MatchCenterRouteChildren = {
  MatchCenterTeamIdRoute: MatchCenterTeamIdRoute,
  MatchCenterIndexRoute: MatchCenterIndexRoute,
}

const MatchCenterRouteWithChildren = MatchCenterRoute._addFileChildren(
  MatchCenterRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AuthRoute: AuthRoute,
  FantasyRoute: FantasyRouteWithChildren,
  MatchCenterRoute: MatchCenterRouteWithChildren,
  NewsRoute: NewsRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  VideosRoute: VideosRoute,
  PlayersPlayerIdRoute: PlayersPlayerIdRoute,
  PlayersIndexRoute: PlayersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
